// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABtWe-0ZIkE9f26ZIOJcrmvStU8p7dVCI',
    appId: '1:994890700262:web:8a37f669c3caf49f367227',
    messagingSenderId: '994890700262',
    projectId: 'chatappflutter-62a8f',
    authDomain: 'chatappflutter-62a8f.firebaseapp.com',
    storageBucket: 'chatappflutter-62a8f.appspot.com',
    measurementId: 'G-DF467S8CL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgI41dnkSL8ZVvPo0gAv589LaVdSgIz6g',
    appId: '1:994890700262:android:d5cea2443fe4e3a5367227',
    messagingSenderId: '994890700262',
    projectId: 'chatappflutter-62a8f',
    storageBucket: 'chatappflutter-62a8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAL49hu5yDT46m2C1-GCmAP8ODcj043RY',
    appId: '1:994890700262:ios:964541c789a04207367227',
    messagingSenderId: '994890700262',
    projectId: 'chatappflutter-62a8f',
    storageBucket: 'chatappflutter-62a8f.appspot.com',
    androidClientId: '994890700262-e2bemb499coo25aaqopvonpesueu5pll.apps.googleusercontent.com',
    iosClientId: '994890700262-p6rlro6c7aemh4f2hvp436asbib04ats.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
